CREATE TABLE ASSINANTE (
	CD_ASSINANTE INT PRIMARY KEY,
	NM_ASSINANTE VARCHAR(100)
);

CREATE TABLE TIPO_ASSINANTE(
	CD_TIPO INT PRIMARY KEY, 
	DS_TIPO VARCHAR(200)
);

CREATE TABLE ASS_TIPO(
	CD_ASSINANTE INT,
	CD_TIPO INT, 
	FOREIGN KEY (CD_ASSINANTE) REFERENCES ASSINANTE(CD_ASSINANTE),
	FOREIGN KEY (CD_TIPO) REFERENCES TIPO_ASSINANTE(CD_TIPO)
);

CREATE TABLE RAMO_ATIVIDADE(
	CD_RAMO INT PRIMARY KEY,
	DS_TIPO VARCHAR(200)
);

CREATE TABLE ENDERECO(
	CD_ENDERECO INT PRIMARY KEY,
	DS_ENDERECO VARCHAR(200),
	COMPLEMENTO VARCHAR(200),
	BAIRRO VARCHAR(100),
	CEP VARCHAR(20)

);

CREATE TABLE ASS_ENDERECO(
	CD_ASSINANTE INT,
	CD_ENDERECO INT,
	FOREIGN KEY (CD_ASSINANTE) REFERENCES ASSINANTE(CD_ASSINANTE),
	FOREIGN KEY (CD_ENDERECO) REFERENCES ENDERECO(CD_ENDERECO)
);

CREATE TABLE MUNICIPIO(
	CD_MUNICIPIO INT PRIMARY KEY,
	DS_MUNICIPIO VARCHAR(100)
);

CREATE TABLE END_MUNICIPIO(
	CD_MUNICIPIO INT, 
	CD_ENDERECO INT,
	FOREIGN KEY (CD_MUNICIPIO) REFERENCES MUNICIPIO(CD_MUNICIPIO),
	FOREIGN KEY (CD_ENDERECO) REFERENCES ENDERECO(CD_ENDERECO)
);

CREATE TABLE TELEFONE(
	CD_FONE INT PRIMARY KEY,
	DDD VARCHAR(3),
	N_FONE VARCHAR(10)
);

CREATE TABLE END_FONE(
	CD_ENDERECO INT,
	CD_FONE INT,
	FOREIGN KEY (CD_ENDERECO) REFERENCES ENDERECO(CD_ENDERECO),
	FOREIGN KEY (CD_FONE) REFERENCES TELEFONE(CD_FONE)
);



