CREATE DATABASE EX17;

USE EX17;


CREATE TABLE TipoImove(
	idtpimovel int primary key,
	tipoImovel varchar(100),
);

CREATE TABLE CIDADE (
	CODCIDADE INT PRIMARY KEY,
	CIDADE VARCHAR(100),
	CAMPO VARCHAR(100)
)
CREATE TABLE PRAIA 